name: Publish
on:
  push:
    tags:
      - v*
jobs:
  test:
    uses: ./.github/workflows/test.yml
  build-linux:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.9"
          enable-cache: true
      - name: Install python
        run: uv python install
      - name: Version
        run: uv version ${{ github.ref_name }}
      - name: Build
        run: uv build
      - name: Publish
        run: uv publish
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.9"
          enable-cache: true
      - name: Install python
        run: uv python install
      - name: Version
        run: uv version ${{ github.ref_name }}
      - name: Build
        run: uv run cxfreeze bdist_msi
      - name: Upload distributable
        uses: actions/upload-artifact@v5
        with:
          name: installer
          path: dist/*
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build-linux, build-windows]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          name: installer
          path: dist
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "$GITHUB_REF_NAME" ./dist/*.msi --repo="$GITHUB_REPOSITORY" --generate-notes
